bremersee:
  security:
    cors:
      allow-all: true
    authentication:
      enable-jwt-support: false
      basic-auth-users:
        - name: ${ACTUATOR_USER_NAME:actuator}
          password: ${ACTUATOR_USER_PASSWORD:actuator}
          authorities:
            - "ROLE_ACTUATOR"
        - name: ${ADMIN_USER_NAME:admin}
          password: ${ADMIN_USER_PASSWORD:${random.value}}
          authorities:
            - "ROLE_ACTUATOR"
            - "ROLE_ACTUATOR_ADMIN"
      actuator:
        roles:
          - "ROLE_ACTUATOR"
        admin-roles:
          - "ROLE_ACTUATOR"
          - "ROLE_ACTUATOR_ADMIN"
  scs:
    content-location: ${CONTENT_LOCATION:classpath:content/}
    root-resource: ${ROOT_RESOURCE:index.html}
    protection: ${PROTECTION_MODE:none}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:framework}

logging:
  level:
    ROOT: info
    org.bremersee: debug
    reactor: info
    org.springframework: info

---

spring:
  profiles: protection-test

bremersee:
  security:
    authentication:
      enable-jwt-support: false
      basic-auth-users:
        - name: actuator
          password: actuator
          authorities:
            - "ROLE_ACTUATOR"
        - name: admin
          password: admin
          authorities:
            - "ROLE_USER"
            - "ROLE_ACTUATOR"
            - "ROLE_ACTUATOR_ADMIN"
        - name: user
          password: user
          authorities:
            - "ROLE_USER"
      actuator:
        roles:
          - "ROLE_ACTUATOR"
        admin-roles:
          - "ROLE_ACTUATOR"
          - "ROLE_ACTUATOR_ADMIN"
      application:
        user-roles:
          - "ROLE_USER"
  scs:
    protection: in_memory
